[workspace]
resolver = "2"
members = [
    "crates/wh-proto",
    "crates/wh-device",
    "crates/wh-config",
    "crates/wh-cli",
    "crates/wh-tui",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
